[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
collateral_vault = "2EMRqcZ82SxuQ7QLEBuF16ppB12UscSHxjsa9muKDa1R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 30000